dubbo:
  provider:
    delay: 3000
  protocol:
    name: dubbo
  application:
    qos-port: -1
#  registry:
#    address: nacos://localhost:8848
#    register-mode: instance
# ???????????????????????? interface?instance?all????? all???????????? instance