spring:
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 1000ms
      #      password:
      #      database:

dubbo:
  provider:
    delay: 3000
  protocol:
    name: dubbo
#  application:
#    qos-port: -1

#  registry:
#    address: nacos://localhost:8848
#    register-mode: instance
    # 新用户请设置此值，表示启用应用级服务发现，可选值 interface、instance、all，默认值为 all，未来版本将切换默认值为 instance



