services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dymall
#      MYSQL_USER: your_user
#      MYSQL_PASSWORD: your_password

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - your_network

  nacos:
    image: nacos/nacos-server:v2.5.0
    container_name: nacos-standalone
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    networks:
      - your_network
#    depends_on:
#      mysql:
#        condition: service_healthy
#    restart: always

  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - your_network


#  prometheus:
#    image: prom/prometheus:latest
#    extra_hosts:
#      - "host.docker.internal:host-gateway"     # allow a direct connection from container to the local machine
#    ports:
#      - "9090:9090"   # the default port used by Prometheus
#    volumes:
#      - ${PWD}/prometheus.yaml:/etc/prometheus/prometheus.yml # mount Prometheus config file
#
#  grafana:
#    image: grafana/grafana:latest
#    depends_on:
#      - prometheus
#    ports:
#      - "3000:3000" # the default port used by Grafana
#  grafana:
#    image: grafana/grafana-enterprise
#    container_name: grafana
#    ports:
#      - "3000:3000"
#
#  prometheus:
#    image: prom/prometheus:latest
##    volumes:
##      - ./deploy/config/prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - "--config.file=/etc/prometheus/prometheus.yml"
#    ports:
#      - "9090:9090"
#
#  k6:
#    image: grafana/k6:latest


networks:
  your_network:

volumes:
  mysql_data: